# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9269d5e47580336811d04585ffa5b6cf7314d3e9c743c5d8fadd8f7e094e0b2d1381e15d163d4e82d1134266653a90ca8a5f3972fa0c204ceac7b2a9b6495f9

test:
  secret_key_base: 57bd8958529d678ad2d2bbd80b38b15abb60e2e60b155cdf238bb633a38a0663120ad7f04a1f80cf28b4dda755a1b28ab8da5f8c4fe40a75d14058f0dff8698f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
